### PR TITLE
Fixed frece ordering in fzf

### PR DESCRIPTION
**Pull request by Baitinq**
I believe this should fix the wrong numbers in fzf

### CODE REVIEW

**Comment by RaitaroH** [comment]
I had to modify this to keep colors. I also added a test for line_number > 10. I have also changed the adl.db dir to .local/share instead.
Thank you for the PR.

**Comment by RaitaroH** [comment]
image
Colored and aligned.

**Comment by Baitinq** [comment]
@RaitaroH Np, what do the colors mean btw?

**Comment by RaitaroH** [comment]
Blue means is airing; white means it finished airing.
(airing might look differently depending on your color scheme idk).

**Comment by RaitaroH** [comment]
Also, a tip: you can do `sed 's/one/two/g ; s/foo/bar/g'` instead of having 2 seds. I also put `tail` in sed as well in order to have a bit more performance. Not like it matters because trackma takes forever ¯\\\_(ツ)\_/¯

**Comment by Baitinq** [comment]
Thanks for the tips!

**Pull request closed without merging**
