### PR TITLE
2.2.1 fetch list after trackma update, #2

### PR DESCRIPTION
**Pull request by RaitaroH**
@Baitinq check out this version and tell me if this fix for #2 is fine. I still consider this is a bit slow.
Alternatively this could be improved by changing the `tlist` variable, so no trackma is needed.

### CODE REVIEW

**Comment by Baitinq** [comment]
True, maybe it would be better to just change the `tlist` var

**Comment by Baitinq** [comment]
@RaitaroH although it doesnt take too much time in my opinion so this could work perfectly fine as well

**Comment by RaitaroH** [comment]
I did consider an option for that using sed... unfortunately it becomes sorta complicate to keep the table aligned. So if I change say 8 to 10 for Casshern this happens. Also, I need to be careful sed doesn't replace something else either like the colors and for that sed gets more complicated. Also this requires another function with basically 3 inputs so it gets sorta messy.

```bash
update_list() { #{{{
      trackma update "$title" "$1"
      color_print "\nUpdating anime list..."
      tlist="$(echo "$tlist" | sed -e "/$title/{s/$(($nr-1))/$1/g}")"
} #}}}
....
      read custom
      trackma send
      update_list $custom
```

image

**Comment by Baitinq** [comment]
@RaitaroH Okay, thats fine. Thanks again for the script!

**Pull request merged**
